### ISSUE TITLE
Possible docker-compose fill to spin up alternative test setup

### ISSUE THREAD

**Issue by florianschmidt1994** [hobbit-project/DEBS-GC-2018#15]
Hello

is it possible to spin-up the local test setup without relying on the java sdk / docker builds in code?
I was in the progress of putting together a compose file and this is what I've gotten so far, but I assume there might be some quirks that one might need to now?

```yaml
version: "3"
services:
  data-generator:
    image: git.project-hobbit.eu:4567/debs_2018_gc/data-generator
    depends_on:
      - rabbit
    environment:
      - QUERY_TYPE=2
      - GENERATOR_LIMIT=72
      - HOBBIT_CONTAINER_NAME=null
      - HOBBIT_GENERATOR_ID=0
      - HOBBIT_RABBIT_HOST=rabbit
      - HOBBIT_GENERATOR_COUNT=1
      - HOBBIT_SESSION_ID=session_1521060139382
      - HOBBIT_GENERATOR_ID=1
      - GENERATOR_TIMEOUT=60
  eval-storage:
    image: git.project-hobbit.eu:4567/debs_2018_gc/eval-storage
    depends_on:
      - rabbit
    environment:
      - QUERY_TYPE=2
      - HOBBIT_EXPERIMENT_URI=http://example.com/exp1
      - SYSTEM_CONTAINER_ID=git.project-hobbit.eu:4567/smirnp/sml-benchmark-v2/system-adapter
      - HOBBIT_CONTAINER_NAME=null
      - HOBBIT_RIAK_NODES=1
      - HOBBIT_RABBIT_HOST=rabbit
      - HOBBIT_SESSION_ID=session_1521060139382
  benchmark-controller:
    image: git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller
    depends_on:
      - rabbit
    environment:
      - HOBBIT_EXPERIMENT_URI=http://example.com/exp1
      - HOBBIT_SESSION_ID=session_1521060139382
      - HOBBIT_CONTAINER_NAME=null
      - HOBBIT_RABBIT_HOST=rabbit
      - 'BENCHMARK_PARAMETERS_MODEL={   "@id" : "http://example.com/exp1",   "generatorLimit" : "72",   "generatorTimeoutMin" : "60",   "queryType" : "2",   "@context" : {     "queryType" : {       "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",       "@type" : "http://www.w3.org/2001/XMLSchema#int"     },     "generatorTimeoutMin" : {       "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorTimeoutMin",       "@type" : "http://www.w3.org/2001/XMLSchema#int"     },     "generatorLimit" : {       "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorLimit",       "@type" : "http://www.w3.org/2001/XMLSchema#int"     }   } }'
  task-generator:
    image: # todo: build locally or have access to image from docker repo
    depends_on:
      - rabbit
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - HOBBIT_GENERATOR_ID=0
      - HOBBIT_GENERATOR_COUNT=1
      - GENERATOR_LIMIT=72
      - GENERATOR_TIMEOUT=60
  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
```
